### PR TITLE
Feature: Filter And Analyze to Obtain Detected Words

### PR DESCRIPTION
**Pull request by mkadirtan**
Added a convenience method that can be used to report which words are detected for data analysis or to keep a log of detected words.

### CODE REVIEW

**Comment by alexzel** [comment]
Thanks  for the contribution. The new method seems to duplicate the most of the code from `filter` function.
I would prefer adding optional callback to the existing method like `filter (str: string, cb?: Function): string` and then call it when it is defined:
```ts
p => {
    if (this.check(p) === true) {
      cb?.(p)
      return this.opts.placeholder
    }
    return p
  }
```
then you can gather words and retrieve the filtered string 
```ts
const detected: string[] = []
const filtered = badwords.filter(str, (word: string) => {
  detected.push(word)
})
```
With the change to the `filter` function by having a callback it seems to me that we do not need `filterAndAnalyze` method as a part of the library b/c it becomes a simple wrapper around `filter` function that can be easily implemented by the library user.

Let me know if it makes sense, and feel free to update the PR.

**Comment by mkadirtan** [comment]
Definitely makes more sense, I will update the PR.

**Comment by mkadirtan** [comment]
Updated according to your comment, can you review again @alexzel

**Comment by alexzel** [comment]
Thanks! I have released v1.6.0 with the changes and quick cleanups.

**Pull request merged**
