### PR TITLE
Update lookalikes in en.json

### PR DESCRIPTION
**Pull request by pbzona**
I think this may have been a typo - if it's intended, it's just something I haven't seen before so feel free to disregard.

Thanks for the great library!

### CODE REVIEW

**Comment by alexzel** [comment]
Well, it's kinda tricky, letter z may look like 3 in some [Typographic variants](https://en.wikipedia.org/wiki/Z), but I acknowledge that it's more like capital E in the modern English writing.

Screen Shot 2024-04-07 at 12 09 36 PM

If you strongly feel that it's more like E, I will merge this PR. Please let me know what you think in this regard.

Thanks for the contribution.

**Comment by alexzel** [comment]
@pbzona any thoughts regarding my last comment above?

**Comment by pbzona** [comment]
Hey @alexzel sorry I missed this. I hadn't considered the lowercase script z, that's very interesting typographically. 

I do think it's more common to see 3 represent an `e` than a `z` in English. When I tried to validate my opinion, I found a research paper (yes really!) that seems to draw the same conclusion. Pretty cool stuff, it's [here](https://www.uv.es/~mperea/leet1.pdf) if you're interested.

Your project, your call, but I do think `e` is the more common substitution.

**Comment by alexzel** [comment]
That's a really interesting paper. Thank you for the elaboration. I'll merge the change and build the release.

**Pull request merged**
